const EventsConstants = {

  WINDOW_RESIZE: 'WINDOW_RESIZE',
  WINDOW_ON_FOCUS: 'WINDOW_ON_FOCUS',
  WINDOW_ON_BLUR: 'WINDOW_ON_BLUR',
  WINDOW_ON_MOUSEMOVE: 'WINDOW_ON_MOUSEMOVE',

  MOUSE_MOVE: 'MOUSE_MOVE',
  MOUSE_DOWN: 'MOUSE_DOWN',
  MOUSE_UP: 'MOUSE_UP',

  SPACE_DOWN: 'SPACE_DOWN',
  SPACE_UP: 'SPACE_UP',

  RESOURCES_PROGRESS: 'RESOURCES_PROGRESS',
  RESOURCES_READY: 'RESOURCES_READY',

  APP_START: 'APP_START',
  ROUTE_CHANGED: 'ROUTE_CHANGED',
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_SUBPAGE: 'CHANGE_SUBPAGE',
  TRANSITION_OUT: 'TRANSITION_OUT',
  TRANSITION_OUT_COMPLETE: 'TRANSITION_OUT_COMPLETE',

  END_AMBIENT: 'END_AMBIENT',
  TUTO_DISPLAY: 'TUTO_DISPLAY',
  GENERATE_ROOMID: 'GENERATE_ROOMID',
  MUTE_ALL: 'MUTE_ALL',

  START_CHAPTER: 'START_CHAPTER',
  CHANGE_CHAPTER: 'CHANGE_CHAPTER',
  PINCH_START: 'PINCH_START',
  PINCH_END: 'PINCH_END',
  PRESS_START: 'PRESS_START',
  PRESS_END: 'PRESS_END',
  ROTATE: 'ROTATE'

}

export default EventsConstants
